# Generated by Django 5.2.4 on 2025-08-02 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2025, 8, 2)),
            preserve_default=False,
        ),
    ]
